[package]
name = "chat-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
argon2 = { version = "0.5.3", features = ["std"] }
axum = { version = "0.7.5", features = [
    "http2",
    "query",
    "tracing",
    "multipart",
] }
axum-macros = "0.4.1"
chrono = { version = "0.4.38", features = ["serde"] }
config = "0.14.0"
jwt-simple = { version = "0.12.9", default-features = false, features = ["pure-rust"] }
serde = { workspace = true }
serde_json = "1.0.117"
serde_yaml = { workspace = true }
sqlx = { workspace = true }
sqlx-db-tester = "0.4.2"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
http-body-util = "0.1.1"
