### chat api
GET http://localhost:8080/api/chats
Authorization: Bearer {{token}}

### signup user
POST http://localhost:8080/api/signup
Content-Type: application/json

{
    "fullname": "jack3",
    "email": "jack3@122.com",
    "password": "123456",
    "workspace": "jack"
}

### signin user
# @name signin
POST http://localhost:8080/api/signin
Content-Type: application/json

{
    "email": "jack@122.com",
    "password": "123456",
    "ws_id": 1
}

@token = {{signin.response.body.token}}


### get users
GET http://localhost:8080/api/users
Authorization: Bearer {{token}}

### create chat
POST http://localhost:8080/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "chat2",
    "members": [1, 2, 3],
    "ws_id": 1,
    "public": true
}

### update chat
PATCH  http://localhost:8080/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "chat1",
    "members": [1, 2, 3],
    "ws_id": 1,
    "public": false
}

### get chat by id
GET http://localhost:8080/api/chats/1
Authorization: Bearer {{token}}

### delete chat
DELETE http://localhost:8080/api/chats/1
Authorization: Bearer {{token}}

### send message
POST http://localhost:8080/api/chats/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "hello",
    "files": []
}

### list messages
GET http://localhost:8080/api/chats/2/messages?limit=10
Authorization: Bearer {{token}}

### upload file
POST http://localhost:8080/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="README.txt"
Content-Type: application/octet-stream

< D:\environment\Maven\apache-maven-3.9.5\README.txt
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"

Hello World!
--MyBoundary--


### get file
GET http://localhost:8080/api/files/1/dd1/82e/8e3f6aba971b999f75f61cdd2d22c56135.txt
Authorization: Bearer {{token}}
