### chat api
GET http://localhost:8080/api/chat
Authorization: Bearer {{token}}

### signup user
POST http://localhost:8080/api/signup
Content-Type: application/json

{
    "fullname": "j1im",
    "email": "jim1@122.com",
    "password": "123456"
}

### signin user
# @name signin
POST http://localhost:8080/api/signin
Content-Type: application/json

{
    "email": "jim@122.com",
    "password": "123456"
}

@token = {{signin.response.body.token}}
